// Generated by CoffeeScript 1.3.3
var app, assets, dir, express, fs, port, stylus, vid;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

dir = process.env.VIDSTREAMDIR;

fs = require('fs');

app = express();

app.use(assets());

app.use(express["static"](dir));

app.use(express.directory(dir));

app.set('view engine', 'jade');

app.get('/', function(req, resp) {
  return resp.render('index');
});

vid = require('vid-streamer');

app.get(/videos/, vid);

vid.settings({
  mode: "Development",
  forceDownload: false,
  random: false,
  rootFolder: dir + '/',
  rootPath: "videos/",
  server: "VidStreamer.js/0.1.2"
});

app.get('/listings', function(req, res) {
  return fs.readdir(dir, function(error, files) {
    if (error) {
      throw error;
    }
    return res.send(200, files);
  });
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
